background            #000077
foreground            #ffffff
cursor                #ffffff

selection_background  #ffff00
selection_foreground  #000077

color0                #000000
color1                #ff0000
color2                #00ff00
color3                #ffff00
color4                #0000ff
color5                #8000ff
color6                #00ffff
color7                #ffffff

color8                #303030
color9                #ff8080
color10               #80ff80
color11               #ffff80
color12               #8080ff
color13               #c081ff
color14               #80ffff
color15               #bbbbbb

active_tab_foreground   #ff0000
active_tab_background   #00ff00
inactive_tab_foreground #ff00ff
inactive_tab_background #00ffff