include color-theme.conf

font_family      family='JetBrainsMonoNL Nerd Font Mono' style=Bold
bold_font        family='JetBrainsMonoNL Nerd Font Mono' style=ExtraBold
italic_font      auto
bold_italic_font auto

text_size 11
background_opacity 1